package com.infoland.test;

import com.infoland.utils.excel.ExcelField;
import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseApply<M extends BaseApply<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCodeOne(java.lang.String codeOne) {
		set("code_one", codeOne);
	}

	@ExcelField(title = "申请书编号1")
	public java.lang.String getCodeOne() {
		return get("code_one");
	}

	public void setCodeTwo(java.lang.String codeTwo) {
		set("code_two", codeTwo);
	}

	@ExcelField(title = "申请书编号2")
	public java.lang.String getCodeTwo() {
		return get("code_two");
	}

	public void setHandleCardType(java.lang.String handleCardType) {
		set("handle_card_type", handleCardType);
	}

	public java.lang.String getHandleCardType() {
		return get("handle_card_type");
	}

	public void setHandleCardValue(java.lang.String handleCardValue) {
		set("handle_card_value", handleCardValue);
	}

	@ExcelField(title = "办理卡种类别")
	public java.lang.String getHandleCardValue() {
		return get("handle_card_value");
	}

	public void setCustomerPhone(java.lang.String customerPhone) {
		set("customer_phone", customerPhone);
	}

	@ExcelField(title = "客户手机号")
	public java.lang.String getCustomerPhone() {
		return get("customer_phone");
	}

	public void setSalesmanCode(java.lang.String salesmanCode) {
		set("salesman_code", salesmanCode);
	}

	@ExcelField(title = "营销员代码")
	public java.lang.String getSalesmanCode() {
		return get("salesman_code");
	}

	public void setWechatId(java.lang.Integer wechatId) {
		set("wechat_id", wechatId);
	}

	public java.lang.Integer getWechatId() {
		return get("wechat_id");
	}

}
